name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 5. Upload APK as artifact (v4)
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AYIKS_Debug_APK
          path: app/build/outputs/apk/debug/app-debug.apk
